apiVersion: v1
kind: Service 
metadata: 
  name: nginx-service 
spec:
  selector:
    app: nginx-pod
  ports:
    # To hit the service on
    - port: 80 
    # To hit the container 
      targetPort: 80