apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -prod

namespace: prod

replicas:
  - name: nginx-deploy
    count: 5

images:
  - name: nginx
    newName: nginx
    newTag: "1.22"

commonAnnotations:
  branch: prod

labels:
  - pairs:
      env: prod
    includeSelectors: true
    includeTemplates: true

